### PR TITLE
Extend database of autotuned and predicted A100 kernels

### PR DESCRIPTION
**Pull request by mkrack**
- 3043 autotuned A100 kernels
- 71048 predicted A100 kernels

### CODE REVIEW

**Comment by dev-zero** [comment]
@mkrack do you see any notable performance improvements?

**Comment by dev-zero** [comment]
ACK from my side: @mkrack unless you want to do it yourself, I will pull the pre-commit.ci fix into their respective commits with [git absorb](https://github.com/tummychow/git-absorb) and force push.

**Comment by mkrack** [comment]
> @mkrack do you see any notable performance improvements?

I do not observe a performance boost on JURECA. There are simply too many CPU cores available per GPU (32 core per A100 while Piz Daint has only 12 cores per P100). On the other hand, you need tuned parameters for an efficient usage of the A100 GPUs, otherwise, it might be better to ignore the GPUs completely.

**Comment by hfp** [comment]
Did anyone try the OpenCL backend?

**Comment by mkrack** [comment]
> ACK from my side: @mkrack unless you want to do it yourself, I will pull the pre-commit.ci fix into their respective commits with [git absorb](https://github.com/tummychow/git-absorb) and force push. Essentially running this after checking out your feature branch:
> 
> ```
> git reset --soft HEAD~1
> git absorb --base develop
> ```

@dev-zero Applied `git-adsorb`, but not sure, if the result is what you wanted?

**Comment by dev-zero** [comment]
> > ACK from my side: @mkrack unless you want to do it yourself, I will pull the pre-commit.ci fix into their respective commits with [git absorb](https://github.com/tummychow/git-absorb) and force push. Essentially running this after checking out your feature branch:
> > ```
> > git reset --soft HEAD~1
> > git absorb --base develop
> > ```
> 
> @dev-zero Applied `git-adsorb`, but not sure, if the result is what you wanted?

Sorry, I forgot the `git rebase -i --autosquash develop` up there (or the `--and-rebase` option for `git absorb`).

**Comment by mkrack** [comment]
> Sorry, I forgot the `git rebase -i --autosquash develop` up there (or the `--and-rebase` option for `git absorb`).

@dev-zero Better you squash the commits.

**Comment by dev-zero** [comment]
> > Sorry, I forgot the `git rebase -i --autosquash develop` up there (or the `--and-rebase` option for `git absorb`).
> 
> @dev-zero Better you squash the commits.

Done. Sorry for the confusion. For completeness, the complete command would have been either

```
# to revert the commit done by the precommit.ci bot back into staged
git reset --soft HEAD~1
# to let git absorb figure out which hunks belong to which commits, commit them as fixups and then do a rebase
# ... if no reference given will automatically use the one from which this branch forked off
git absorb --and-rebase
```

or if manual control is wanted:

```
git reset --soft HEAD~1
# only generate commits
git absorb
# do the rebase with squash separately
git rebase -i --autosquash develop
```

**Pull request merged**
