### PR TITLE
Update .gitignore after AMD port

### PR DESCRIPTION
**Pull request by shoshijak**
See #271.

### CODE REVIEW

**Comment by shoshijak** [comment]
retest this please

**Comment by alazzaro** [comment]
> Travis/OSX build is failing.

Please rebase, Tiziano fixed this problem

**Comment by alazzaro** [comment]
@shoshijak 
One more thing, I see a sym link to a file 

https://github.com/cp2k/dbcsr/blob/develop/src/acc/libsmm_acc/notebooks/libsmm_acc_parameters_and_memory.png

which points to anything. Is this expected?

**Comment by shoshijak** [comment]
A symlink is needed there, in order to visualise the PNGs in `dbcsr/docs/images` from within the notebooks. That being said, there was a typo in the symlink andI just fixed it. Thanks!

**Comment by alazzaro** [comment]
OK, then it is ready to merge?

**Comment by shoshijak** [comment]
Yes, do we want to wait for the checks to complete, though? 
(Even though the files touched in this PR shouldn't affect the build/run at all)

**Comment by alazzaro** [comment]
Well, I'm checking on Daint with the dashboard, let me do a complete check ;) no need to wait for the CI...

**Pull request merged**
