### PR TITLE
Issue #261: apply -hnoacc flag

### PR DESCRIPTION
**Pull request by hfp**
I am not completely certain about this PR, but perhaps good enough.

### CODE REVIEW

**Comment by alazzaro** [comment]
I'm not sure, but likely it requires a space between -M and the number?
However, I'm not sure the CC-1234 is a warning, so we cannot suppress it...

**Comment by hfp** [comment]
I tried with and without space: "invalid characters after -M". Anyhow, the `cc` binary on Archer (as figured/used by CMake) did not want any such option not even the deployed suppression (`-M3105`). However, I did not check with `ftn`. I am certain that CMake was using v8.8.7 as the path to the binary also included the version number.

**Comment by alazzaro** [comment]
So, the conclusion is: the `-hnoacc` is good to have, but it doesn't solve the problem. Right?
The only solution is to rename the function... This PR can be merged anyway...

**Comment by hfp** [comment]
I can confirm, `-M` flag is Fortran specific (`ftn`). I think, this can be worked out for C/C++ as well: [https://pubs.cray.com/content/S-2179/8.7/cray-c-and-c++-reference-manual/message-options](https://pubs.cray.com/content/S-2179/8.7/cray-c-and-c++-reference-manual/message-options). Let me try this and updated this PR.

**Pull request merged**
