### PR TITLE
Tuned H100 kernels

### PR DESCRIPTION
**Pull request by abussy**
Tuned H100 kernels, with the tuning taking place on the new CSCS Alps (Santis) machine.
The set of tuned kernels covers the same space as the auto-tuned A100 kernels, but none of the A100 predicted kernels.
The new DBCSR generic kernels should fill the void well enough.

All DBCSR correctness [tests](https://github.com/cp2k/dbcsr/tree/develop/tests#gpu-backend-correctness-tests) passed successfully with the new H100 kernels.

### CODE REVIEW

**Comment by alazzaro** [comment]
@abussy Great! Should I proceed to make the final release?

**Comment by abussy** [comment]
From my side, we can go ahead to the release.

**Comment by alazzaro** [comment]
I seems the new kernels were not included in the JIT generation (see https://github.com/cp2k/dbcsr/commit/6b2109e2d103fdf5b26c6a14eabd1bbd1226b85c). Could you confirm that you get a warning that the kernels were not generated?

**Comment by abussy** [comment]
I re-ran all DBCSR correctness tests with the latest commit, and everything is successful. I am concurrently running the CP2K regtests, and so far, everything passes as well.

**Pull request merged**
