### PR TITLE
reformat all file headers

### PR DESCRIPTION
**Pull request by dev-zero**
fixes: #3

### CODE REVIEW

**Comment by dev-zero** [comment]
Don't care much about it, but I removed the right-side part since I got tired when editing the banner and it is just decoration.
The dot after the URL on the other hand is really annoying when copy/pasting.

**Comment by oschuett** [comment]
As I said just some suggestions. The final dot on the url makes it (technically) more accurate, but I see that it could confuse people. As for the decoration, I simply like symmetry ;-)

**Comment by alazzaro** [comment]
I don't have any comment, it is fine with me. The only thing is that we have to update the header on the .h, .cu, .py files (and any other code extension).

**Comment by dev-zero** [comment]
ok, updated the PR based on the discussion, also added headers for `.py`, `.cu` and `.cpp`, please merge if you agree

**Comment by oschuett** [comment]
Thanks for keeping the decoration :-)

**Pull request merged**
