### PR TITLE
Avoid Ctx API in HIP backend

### PR DESCRIPTION
**Pull request by gsitaram**
Tested some unit tests and perf_test and they seem to run fine without these API calls on AMD GPUs. Context APIs are now deprecated in newer versions of ROCm, and functionality is satisfied by hipSetDevice() API call. Please review and merge.
cc: @alazzaro

### CODE REVIEW

**Comment by alazzaro** [comment]
@gsitaram thanks for this PR, however I would like to ask you 2 changes:

- we need this change only for recent HIP versions (according to https://github.com/cp2k/dbcsr/issues/783#issuecomment-2070790452 this is starting with version 6.1)
- we can revert the change I did at https://github.com/cp2k/dbcsr/pull/792, namely we can remove those lines 

https://github.com/cp2k/dbcsr/blob/3d5549904aaedb5191b3195107d491443fb1ce6c/cmake/CompilerConfiguration.cmake#L54-L56

**Comment by gsitaram** [comment]
@alazzaro, why do we need these ctx APIs for any version of ROCm? I would like to avoid those APIs completely. In that case, only unwinding your fixes in [https://github.com/cp2k/dbcsr/pull/792](https://github.com/cp2k/dbcsr/pull/792)** would be sufficient, and I have done that now.

**Comment by alazzaro** [comment]
> @alazzaro, why do we need these ctx APIs for any version of ROCm? I would like to avoid those APIs completely. In that case, only unwinding your fixes in #792** would be sufficient, and I have done that now.

Personally, I have no idea what those functions do. There were there for the AMD backend since ages, so my assumption was that we need them for the Rocm 5.x... Now, if you tell me that we can drop them for all ROCM versions, then I'm fine with that ;)

**Comment by gsitaram** [comment]
Thank you, @alazzaro . I think we should be fine. Let me know if you encounter issues that may be related to this.

**Pull request merged**
