### PR TITLE
Complement enabling ACC timers for non-ACC compilation

### PR DESCRIPTION
**Pull request by hfp**

### CODE REVIEW

**Comment by alazzaro** [comment]
Thanks!

**Comment by hfp** [comment]
> Thanks!

No problem (hopefully this fixes https://buildkite.com/intel/dbcsr/builds/804).

**Comment by alazzaro** [comment]
But why the CI doesn't face this error? Is it something we don't build via cmake?

**Comment by hfp** [comment]
> But why the CI doesn't face this error? Is it something we don't build via cmake?

I guess both `acc_bench_smm` and `acc_bench_trans` are not build and exercised (completely stand-alone). Regarding `dbcsr_acc_test`, I think dbcsr library is linked when using CMake based build. So, the issue solved here is mostly related to my Makefile based backend specific builds/tests (OpenCL and CUDA). However, this change introduced a dependency criticized earlier. A setter for timer function-pointers is perhaps preferable and avoiding the backends to depend on DBCSR/frontend.

**Comment by hfp** [comment]
I will eventually send another PR contributing `acc_bench_smm` and `acc_bench_trans` to be build with CMake.

**Pull request merged**
