### PR TITLE
tests: add dbcsr_unittest3 to test libcusmm-backend

### PR DESCRIPTION
**Pull request by shoshijak**
Add a matrix-matrix multiplication test which features block-sizes commonly used in libcusmm.
Closes issue #131 

Sample of test output: 
```
 -------------------------------------------------------------------------------
 -                                                                             -
 -                                DBCSR STATISTICS                             -
 -                                                                             -
 -------------------------------------------------------------------------------
 COUNTER                                    TOTAL       BLAS       SMM       ACC
 flops    13 x     4 x     4             59938944      74.0%      0.0%     26.0%
 flops     4 x    13 x     4             60162752      74.3%      0.0%     25.7%
 flops     4 x     4 x    13             60968960      73.9%      0.0%     26.1%
 flops    25 x     4 x     4            114982400      73.9%      0.0%     26.1%
 flops     4 x    25 x     4            115664800      74.2%      0.0%     25.8%
 flops     4 x     4 x    25            117375200      73.2%      0.0%     26.8%
 flops    14 x    14 x    14            162516144      73.8%      0.0%     26.2%
 flops    13 x     4 x    13            195892632      74.3%      0.0%     25.7%
 flops     4 x    13 x    13            197118896      73.9%      0.0%     26.1%
 flops    13 x    13 x     4            198487120      73.9%      0.0%     26.1%
 flops    14 x    29 x    14            324215360      74.2%      0.0%     25.8%
 flops    14 x    14 x    29            326750424      73.8%      0.0%     26.2%
 flops    29 x    14 x    14            328535200      74.2%      0.0%     25.8%
 flops     4 x     4 x     4            338922368      74.0%      0.0%     26.0%
 flops    14 x    32 x    14            365833216      74.3%      0.0%     25.7%
 flops    32 x    14 x    14            367213056      74.4%      0.0%     25.6%
 flops    14 x    14 x    32            370800640      73.5%      0.0%     26.5%
 flops    13 x    25 x     4            374740600      74.2%      0.0%     25.8%
 flops    25 x     4 x    13            376090000      74.4%      0.0%     25.6%
 flops     4 x    13 x    25            376633400      73.6%      0.0%     26.4%
 flops    13 x     4 x    25            377325000      74.0%      0.0%     26.0%
 flops    25 x    13 x     4            380484000      73.8%      0.0%     26.2%
 flops     4 x    25 x    13            381056000      73.9%      0.0%     26.1%
 flops     4 x     5 x     4            399021760      74.2%      0.0%     25.8%
 flops     5 x     4 x     4            399664320      74.1%      0.0%     25.9%
 flops     4 x     4 x     5            400521760      74.1%      0.0%     25.9%
 flops     8 x     5 x     5            407739200      73.8%      0.0%     26.2%
 flops     5 x     8 x     5            408470000      74.2%      0.0%     25.8%
 flops     5 x     5 x     8            411421200      74.1%      0.0%     25.9%
 flops     9 x     5 x     5            456588900      73.8%      0.0%     26.2%
 flops     5 x     9 x     5            460639350      74.3%      0.0%     25.7%
 flops     5 x     5 x     9            461559600      73.8%      0.0%     26.2%
 flops     4 x     5 x     5            499300000      74.1%      0.0%     25.9%
 flops     5 x     4 x     5            501096400      73.9%      0.0%     26.1%
 flops     5 x     5 x     4            501290400      74.1%      0.0%     25.9%
 flops     7 x     4 x     4            557860128      74.3%      0.0%     25.7%
 flops     4 x     7 x     4            560118272      74.0%      0.0%     26.0%
 flops     4 x     4 x     7            560981568      74.1%      0.0%     25.9%
 flops    13 x    13 x    13            645192990      73.9%      0.0%     26.1%
 flops     5 x     8 x     8            651465600      74.3%      0.0%     25.7%
 flops    14 x    29 x    29            656235664      74.9%      0.0%     25.1%
 flops     8 x     5 x     8            657421440      74.0%      0.0%     26.0%
 flops     8 x     8 x     5            658883200      73.9%      0.0%     26.1%
 flops    29 x    14 x    29            671706700      73.9%      0.0%     26.1%
 flops    29 x    29 x    14            677287576      73.8%      0.0%     26.2%
 flops     5 x     7 x     4            698988080      74.1%      0.0%     25.9%
 flops     4 x     5 x     7            699427680      74.1%      0.0%     25.9%
 flops     4 x     7 x     5            699665680      74.1%      0.0%     25.9%
 flops     7 x     5 x     4            699746880      74.3%      0.0%     25.7%
 flops     5 x     4 x     7            701192520      74.2%      0.0%     25.8%
 flops     7 x     4 x     5            702969680      74.1%      0.0%     25.9%
 flops    25 x     4 x    25            724590000      73.7%      0.0%     26.3%
 flops     4 x    25 x    25            727840000      73.8%      0.0%     26.2%
 flops    25 x    25 x     4            732005000      73.7%      0.0%     26.3%
 flops     5 x     8 x     9            733763520      74.1%      0.0%     25.9%
 flops     8 x     9 x     5            734892480      74.2%      0.0%     25.8%
 flops    14 x    32 x    29            735425152      74.2%      0.0%     25.8%
 flops     9 x     5 x     8            736548480      74.0%      0.0%     26.0%
 flops     8 x     5 x     9            736847280      73.9%      0.0%     26.1%
 flops     5 x     9 x     8            738001440      74.0%      0.0%     26.0%
 flops     9 x     8 x     5            738002880      73.9%      0.0%     26.1%
 flops    14 x    29 x    32            738205440      74.6%      0.0%     25.4%
 flops    29 x    32 x    14            745143168      74.5%      0.0%     25.5%
 flops    32 x    14 x    29            747637632      74.5%      0.0%     25.5%
 flops    32 x    29 x    14            751873024      74.0%      0.0%     26.0%
 flops    29 x    14 x    32            768788608      73.8%      0.0%     26.2%
 flops    32 x    14 x    32            812191744      73.3%      0.0%     26.7%
 flops     9 x     5 x     9            829022040      73.9%      0.0%     26.1%
 flops     9 x     9 x     5            830765160      73.9%      0.0%     26.1%
 flops     5 x     9 x     9            834152580      73.9%      0.0%     26.1%
 flops    14 x    32 x    32            841523200      74.0%      0.0%     26.0%
 flops    32 x    32 x    14            853450752      73.9%      0.0%     26.1%
 flops     5 x     7 x     5            875309400      73.9%      0.0%     26.1%
 flops     5 x     5 x     7            881417250      74.0%      0.0%     26.0%
 flops     7 x     5 x     5            882801500      73.9%      0.0%     26.1%
 flops     5 x     5 x     5            884788750      73.8%      0.0%     26.2%
 flops     7 x     4 x     7            976441816      74.2%      0.0%     25.8%
 flops     7 x     7 x     4            981991752      74.1%      0.0%     25.9%
 flops     4 x     7 x     7            982408056      74.2%      0.0%     25.8%
 flops     8 x     8 x     8           1050655744      73.9%      0.0%     26.1%
 flops     9 x     8 x     8           1179266688      74.0%      0.0%     26.0%
 flops     8 x     9 x     8           1179484416      73.9%      0.0%     26.1%
 flops     8 x     8 x     9           1182620160      74.0%      0.0%     26.0%
 flops    13 x    25 x    13           1223610700      74.4%      0.0%     25.6%
 flops     7 x     5 x     7           1227066330      74.1%      0.0%     25.9%
 flops     5 x     7 x     7           1227486750      74.3%      0.0%     25.7%
 flops     7 x     7 x     5           1236699730      73.9%      0.0%     26.1%
 flops    13 x    13 x    25           1237494050      73.7%      0.0%     26.3%
 flops    25 x    13 x    13           1238888300      74.1%      0.0%     25.9%
 flops     9 x     8 x     9           1330182000      73.9%      0.0%     26.1%
 flops     8 x     9 x     9           1331461152      73.9%      0.0%     26.1%
 flops     9 x     9 x     8           1333743408      73.8%      0.0%     26.2%
 flops    29 x    29 x    29           1384661086      74.0%      0.0%     26.0%
 flops     9 x     9 x     9           1512979722      73.6%      0.0%     26.4%
 flops    29 x    32 x    29           1519074752      74.1%      0.0%     25.9%
 flops    32 x    29 x    29           1552337984      74.7%      0.0%     25.3%
 flops    29 x    29 x    32           1585332096      74.0%      0.0%     26.0%
 flops    32 x    29 x    32           1664401408      73.9%      0.0%     26.1%
 flops     7 x     7 x     7           1721966330      74.1%      0.0%     25.9%
 flops    29 x    32 x    32           1739591680      74.1%      0.0%     25.9%
 flops    32 x    32 x    29           1753548800      73.8%      0.0%     26.2%
 flops    32 x    32 x    32           1885929472      73.0%      0.0%     27.0%
 flops    13 x    25 x    25           2347377500      74.4%      0.0%     25.6%
 flops    25 x    13 x    25           2374043750      73.6%      0.0%     26.4%
 flops    25 x    25 x    13           2384476250      74.1%      0.0%     25.9%
 flops    25 x    25 x    25           4587656250      73.9%      0.0%     26.1%
 flops inhomo. stacks                           0       0.0%      0.0%      0.0%
 flops total                        88.326028E+09      74.0%      0.0%     26.0%
 flops max/rank                     22.767165E+09      74.0%      0.0%     26.0%
 matmuls inhomo. stacks                         0       0.0%      0.0%      0.0%
 matmuls total                           99988158      74.0%      0.0%     26.0%
 number of processed stacks                300108      73.3%      0.0%     26.7%
 average stack size                                   336.6       0.0     323.7
 marketing flops                   364.917031E+09
 -------------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by oschuett** [comment]
How about also adding 23? It used to be our poster child as it corresponds to a water molecule.

**Comment by shoshijak** [comment]
Sure, I'll do that

**Comment by alazzaro** [comment]
Great! Thanks! I think we should have these for the CPU too, i.e. do not need to be specific for the GPU.

**Comment by shoshijak** [comment]
Right now `dcsr_unittest3` gets compiled only when the Makefile variable `NVCC` is defined. 
@alazzaro should I change so it gets compiled by default, even when `NVCC` is not defined?

**Comment by alazzaro** [comment]
@shoshijak yes, correct, thanks.

**Pull request merged**
