### PR TITLE
fix dense gpu

### PR DESCRIPTION
**Pull request by dithillobothrium**
fixed memory indexation.

### CODE REVIEW

**Comment by dithillobothrium** [comment]
Apple tests stopped.

**Comment by alazzaro** [comment]
test please

**Comment by alazzaro** [comment]
retest this please

**Comment by dithillobothrium** [comment]
I did not understand. You changed back?

**Comment by alazzaro** [comment]
Wait, working in progress... I've added a test and I'm checking if it is good to trigger the problem... Then I will put back the fix.

**Comment by alazzaro** [comment]
retest this please

**Comment by alazzaro** [comment]
retest this please

**Pull request merged**
