### PR TITLE
updated daint-ci

### PR DESCRIPTION
**Pull request by hfp**
Account for an [updated](https://github.com/cp2k/dbcsr/pull/437#issuecomment-801154121) Daint-CI (CMake, etc), and counter `-Werror` with newer GNU Compiler (certain translation units).

( Unrelated: updated LIBXSMM. )

### CODE REVIEW

**Comment by alazzaro** [comment]
@hfp CSCS introduced a new module for the gpu:

```
module load cdt-cuda
```

**Comment by alazzaro** [comment]
Concerning the `-Wno-error`, we had already a discussion about that and we really want to avoid it.
The problem is introduced in GCC 10.x (however ctd-gpu will load GCC 9.x, since CUDA doesn't support GCC 10 yet).
So, could you revert your commits?
For the GCC 10 rank issue, the problem comes with some MPI (this is the case for the Cray-mpich installed on Daint). @dev-zero proposed [this solution](https://github.com/cp2k/dbcsr/issues/416).

**Comment by hfp** [comment]
> Concerning the `-Wno-error`, we had already a discussion about that and we really want to avoid it.

I am applying `-Wno-error` specifically for the MPI wrapper and one of the examples. Even with GCC 10.x, we preserve `-Werror` for the entire source code base, and still produce warnings for the issue in question (log output). Do you think this solution is acceptable?

> The problem is introduced in GCC 10.x (however ctd-gpu will load GCC 9.x, since CUDA doesn't support GCC 10 yet).
> So, could you revert your commits?

ACK, I will adjust the build scripts. I think we can nevertheless keep the above relaxation about warning-errors for those who want to use GCC 10.x (without CUDA).

> For the GCC 10 rank issue, the problem comes with some MPI (this is the case for the Cray-mpich installed on Daint). @dev-zero proposed [this solution](https://github.com/cp2k/dbcsr/issues/416).

ACK, makes sense. I remember there was also a proposal to wrap things in C. The MPI-F08 module is also supposedly type-safe, but that's another discussion (similar to a C based wrapper).

**Comment by hfp** [comment]
( Coverage dropped by 5% with no source change while Codecov has its own environment. )

**Comment by dev-zero** [comment]
> ( Coverage dropped by 5% with no source change while Codecov has its own environment. )

Codecov is still missing at least one of the tests (hence no post here from the bot and the coverage diff)

**Comment by alazzaro** [comment]
> > Concerning the `-Wno-error`, we had already a discussion about that and we really want to avoid it.
> 
> I am applying `-Wno-error` specifically for the MPI wrapper and one of the examples. Even with GCC 10.x, we preserve `-Werror` for the entire source code base, and still produce warnings for the issue in question (log output). Do you think this solution is acceptable?
>

This is OK, but please extend the check to only GCC >=10.x. The Daint test is to really cover all possible problems, we want to check all warnings... Then, we will make the change more automatic by adopting the @dev-zero solution...

**Comment by hfp** [comment]
> This is OK, but please extend the check to only GCC >=10.x. The Daint test is to really cover all possible problems, we want to check all warnings... Then, we will make the change more automatic by adopting the @dev-zero solution...

ACK. I am just waiting for current Daint-CI to finish.

**Pull request merged**
