### PR TITLE
ocl: ensure compatibility with LIBXSMM 2.0

### PR DESCRIPTION
**Pull request by hfp**
* Updated LIBXSMM (Daint-CI).

### CODE REVIEW

**Comment by hfp** [comment]
CI is a concern as the CI or the code base is rapidly aging (maintenance). If we treat warnings as errors, the code base is not immune against newer compilers and dependencies (if newer compilers/dependencies are picked up by CI).

```text
/opt/rocm-5.5.0/include/hipblas.h:16:2: error: #warning "This file is deprecated. Use the header file from /opt/rocm-5.5.0/include/hipblas/hipblas.h by using #include <hipblas/hipblas.h>" [-Werror=cpp]
   16 | #warning "This file is deprecated. Use the header file from /opt/rocm-5.5.0/include/hipblas/hipblas.h by using #include <hipblas/hipblas.h>"
      |  ^~~~~~~
cc1plus: all warnings being treated as errors
```

... which means, ROCm builds are now failing for reasons unrelated to contributions or this PR.

**Comment by dev-zero** [comment]
@hfp yes, software needs constant upkeep. Todays warnings are tomorrows errors.
We could pin versions, but then we let our users discover the errors.
For `pre-commit` configuration and Python deps, the dependabot approach is nice, will do periodic scans for new versions and create PRs to pull. Allowing a stable CI env and making sure deps get updated periodically.

**Comment by hfp** [comment]
> @hfp yes, software needs constant upkeep. Todays warnings are tomorrows errors. We could pin versions, but then we let our users discover the errors. For `pre-commit` configuration and Python deps, the dependabot approach is nice, will do periodic scans for new versions and create PRs to pull. Allowing a stable CI env and making sure deps get updated periodically.

Thanks!  Btw, #650 looks good, and I will let this PR wait for it.

**Comment by dev-zero** [comment]
merged the fixes (with a separate PR)

**Pull request merged**
