### PR TITLE
Build acc_bench drivers as part of the tests

### PR DESCRIPTION
**Pull request by hfp**
* Fixed warning about unused variable.

### CODE REVIEW

**Comment by hfp** [comment]
The additional targets still link against dbcsr library. So, an issue like https://github.com/cp2k/dbcsr/pull/590#issuecomment-1075597791 would be still not reproduced. For the latter, more work is needed like building a dbcsr_acc library (like pre-CMake time).

**Comment by hfp** [comment]
Final push will remove https://github.com/cp2k/dbcsr/commit/a2bedce43c925591ac1de64da9e044897ae8b61d#diff-38405a63679b1bd07fa830ce45808a408bc7f0c367d57ce2a814061fe01e6e03R57.

**Comment by alazzaro** [comment]
No sure I follow the discussion here...  The two acc_bench drivers are built as standalone package via makefile, i.e. they don't depend on the full DBCSR built. I like the idea to have them as part of the tests. But why we want to keep them standalone? Note that in the long run cmake will be the only way to build DBCSR...

**Comment by alazzaro** [comment]
On the other hand, would it be possible to introduce an OpenCL build on the CI (just like we do for HIP)?

**Comment by alazzaro** [comment]
Let's wait on this PR, I have to understand better...

**Pull request merged**
