### PR TITLE
Cleanup of unused variables

### PR DESCRIPTION
**Pull request by hfp**

### CODE REVIEW

**Comment by hfp** [comment]
I cannot access the CI-log on Daint and do not know what went wrong.

**Comment by alazzaro** [comment]
retest please

**Comment by alazzaro** [comment]
> I cannot access the CI-log on Daint and do not know what went wrong.

It seems a problem on Jenkins on Daint... I'm rerunning it...

**Comment by alazzaro** [comment]
retest this please

**Comment by alazzaro** [comment]
Nothing, still crashing... @dev-zero any clue?

**Comment by dev-zero** [comment]
the error is partially on the Jenkins/GitHub side: @pseewald created a branch on the DBCSR repo with the name `pr`, but this is used as a namespace by the Jenkins GitHub plugin for pulling PR's (they have the path `pr/123/merge`). And now this fails since `pr/` is already a branch name.

@pseewald I've removed your `pr` branch on the DBCSR repo.

**Comment by dev-zero** [comment]
retest this please

**Comment by dev-zero** [comment]
I'm thinking of setting up a storage bucket on Amazon, Google or maybe Switch or the UZH to mirror the reports there to make them accessible to everyone...

**Comment by oschuett** [comment]
We can setup a bucket in the GCP project that I use for the cp2k-ci.

**Pull request merged**
